// Zuri System · "Every screen, every field" — the long walkthrough, one chapter per screen · v1 · 2026-10-01
// Plays as the partner (sees everything), in practice. Chapters chain into one long video; ✕ stops any time.
(function () {
  const Z = window.Z;
  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
  const tap = (sel) => async () => { const e = typeof sel === 'function' ? sel() : [...document.querySelectorAll(sel.split('::')[0])].find((x) => !sel.includes('::') || x.textContent.toLowerCase().includes(sel.split('::')[1].toLowerCase())); if (e) e.click(); await sleep(600); };
  const G = 'Every screen, every field';
  const C = (id, title, mins, next, steps) => ({ id, group: G, title, mins, role: 'admin', next, steps, turn: [] });

  const CH = [
    C('fields-home', '1 · Home', 2, 'fields-tasks', [
      { go: 'home', el: '#hdr', say: 'Chapter one: Home. At the top: who you are, and the area picker. All areas shows the whole company; pick Zuri A or Zuri B to see one area only. Every screen follows this choice.' },
      { el: '#view a.card', say: 'The Zuri manager card: when it last ran, how many things are on your list, and its warnings for today.' },
      { el: '#view .alert', say: 'Needs attention: the most important problems, most urgent first. Each one is a link to the screen where you fix it.' },
      { el: '#view .kpis', say: 'Customers: active customers, how many are paid up, how many have run out, the monthly recurring revenue if everyone pays, renewals due in the next seven days, and customers with no map pin.' },
      { el: '#view .card::Packages', say: 'Packages: how many customers are on each package, and the money each package brings in per month.' },
      { el: 'h3::Service', say: 'Service: open faults and how many were fixed this month, installs waiting, visits today and this week, overdue visits, and payment follow-ups.' },
      { el: '#view .list', say: 'Under it, the next service jobs, with the day and the technician. Tap one to open it.' },
      { el: 'h3::Money', say: 'Money, for finance and partners only: cash now from the last count, the lowest point in the next thirty days, cash in thirty days, bills still owing, and last month\'s profit from the statements.' },
      { el: '#h-cash', say: 'The chart: the cash balance day by day for the next month. Green bars are renewals coming in, red bars are bills going out.' },
      { el: '#h-sales', say: 'Sales from the billing website, month by month: subscriptions against hotspot.' },
      { el: '#h-books', say: 'And income against expenses from the sorted statements. Tap refresh at the top right to reload all of it.' },
    ]),
    C('fields-tasks', '2 · Tasks', 3, 'fields-jobs', [
      { go: 'tasks/mine', el: '.subtabs', say: 'Chapter two: Tasks. Four parts: My day, Team, Add a task, and for finance, WhatsApp nudges and the Manager log.' },
      { el: '#tk-run', say: 'Partners also get Run the manager now, which runs the morning rules on the spot.' },
      { el: '#tk-body .item', say: 'A task: the tick box, the title, who it is for, where it came from, when it is due, and a lock if only finance can see it.' },
      { el: '.tk-cm', say: 'Open, if the task points at a page or a customer, and Notes to talk about it.' },
      { go: 'tasks/team', el: '#tk-who', say: 'Team: everyone\'s open tasks, grouped by person. Filter by a group or a person here.' },
      { el: '#tk-showdone', say: 'Show done brings back the last seven days of finished tasks.' },
      { go: 'tasks/add', el: 'input[name=title]', say: 'Add a task. What needs doing: a few plain words.' },
      { el: 'textarea[name=details]', say: 'Details: anything that helps them do it. Optional.' },
      { el: 'select[name=for]', say: 'Who should do it: yourself, a person, or a whole group, like Field techs or Finance.' },
      { el: 'input[name=due_date]', say: 'Due: the day. Leave it blank for whenever.' },
      { el: 'select[name=priority]', say: 'Priority: normal, high, urgent or low. High and urgent go to the top of their list.' },
      { el: 'input[name=finance]', say: 'Money task: tick this and only finance and the partners can see it.' },
      { go: 'tasks/nudges', el: '#tk-body .item', say: 'WhatsApp nudges: the morning message for each person who has a phone number on their account. Open WhatsApp, send it, Mark sent.' },
      { go: 'tasks/runs', el: '#tk-body .item', say: 'The Manager log: every run, what it created, closed and escalated, and its warnings.' },
    ]),
    C('fields-jobs', '3 · Jobs and a new job', 3, 'fields-job', [
      { go: 'jobs', el: '.subtabs', say: 'Chapter three: Jobs. To do, Done, or All.' },
      { el: '#j-q', say: 'Search by the customer\'s name, their phone, or the job number. It filters as you type.' },
      { el: '#j-tech', say: 'All techs, or one technician\'s jobs.' },
      { el: '#j-list .item', say: 'A job row: a red dot if urgent, the customer, the job number, the kind of job and the problem, the area and landmark, the technician, the visit day, and the status.' },
      { el: '#j-follow', say: 'Payment follow-ups open by themselves each morning. Check now runs that check straight away.' },
      { go: 'jobs/new', el: '#nj-q', say: 'New job. Customer: type a name, phone or account number and tap the right one. Leave it empty for a new-install enquiry.' },
      { el: 'select[name=area]', say: 'Area, and the type of job: fault, new install, payment follow-up, move connection, disconnect, site survey, or other.' },
      { el: 'textarea[name=summary]', say: 'What is wrong or needed, in the customer\'s words.' },
      { el: 'input[name=caller]', say: 'Caller name and phone, if the person calling is not the customer.' },
      { el: 'select[name=priority]', say: 'Priority: normal, urgent or low.' },
      { el: '#nj-tech', say: 'Send to tech: choose the technician, or leave it for later. And the visit day.' },
      { el: '#nj button[type=submit]', say: 'Save job puts it on the technician\'s list straight away.' },
    ]),
    C('fields-job', '4 · Inside a job', 4, 'fields-customers', [
      { go: 'jobs', el: '#j-list .item::no internet', say: 'Chapter four: inside a job. Let\'s open a fault.', do: tap('#j-list .item::no internet') },
      { el: 'h2', say: 'The job number, the kind, and the status: waiting for a tech, assigned, in progress, done, or cancelled.' },
      { el: '#view .card::Problem', say: 'The problem, as the customer described it.' },
      { el: 'a[href^="tel:"]', say: 'The customer card: name, area, account, package and rate, when their payment runs out, the landmark, and Call buttons for each phone number.' },
      { el: '#jd-pin', say: 'Open map and Send pin, if there is a pin. Drop pin here, or Move pin, saves where the technician is standing.' },
      { el: '#jd-disp select[name=assigned_to]', say: 'Who\'s going, and when: the technician, the visit day, and the priority. Save, Cancel job, or Reopen.' },
      { el: '.chips[data-for=findings]', say: 'The work. What did you find: tap the round buttons, or type.' },
      { el: '.chips[data-for=work_done]', say: 'What did you do: the same.' },
      { el: '#jd-paid', say: 'Did the customer pay you: No, Cash, or M-Pesa. Then how much, and for M-Pesa, the code from the customer\'s message.' },
      { el: 'button[data-status=done]', say: 'Job finished closes it. I\'m starting now marks it in progress. Save for later keeps what you typed.' },
      { el: '#jd-part', say: 'Parts and equipment: the item, its serial number if it has one, and how many. Remove takes one off.' },
      { el: 'label.btn::Add photo', say: 'Photos: add a picture of the problem and the finished work.' },
      { el: '#jd-note', say: 'Notes: everything that happened on this job, by whom and when. Add a note at the bottom.' },
      { go: 'jobs', el: '#j-list .item::Payment follow-up', say: 'A payment follow-up has one more card.', do: tap('#j-list .item::Payment follow-up') },
      { el: '#jd-out', say: 'After the call: No answer, Will pay with a day, Says paid, or Wants to stop. And a ready-made WhatsApp reminder.' },
    ]),
    C('fields-customers', '5 · Customers', 4, 'fields-money-today', [
      { go: 'customers', el: '#c-q', say: 'Chapter five: Customers. Search by name, phone or account number.' },
      { el: '#c-st', say: 'Filter by status: active, lead, suspended, disconnected, or any.' },
      { el: '#view .list .item', say: 'A customer row: name, phone, account, package, area, landmark, and a warning if there is no map pin. Fifty per page.' },
      { el: 'a[href="#customers/map"]', say: 'Map shows every customer with a pin, green if paid up, red if they ran out, for the area chosen at the top. New customer adds one by hand; most come in from the billing website.' },
      { el: '#view .list .item', say: 'Open one.', do: tap('#view .list .item') },
      { el: 'h2', say: 'The customer: name and status, area and landmark.' },
      { el: '#cp-pin', say: 'Call, Map, Send pin, Drop pin here, New job for this customer, and Edit.' },
      { el: '#view table.t', say: 'Their details: phone numbers, email, account number, billing website ID, ID number, package and rate, paid until, install date, and any custom fields. Field techs see only what the admin allows.' },
      { el: 'h3::Payments', say: 'Payments: every payment we know of, with the date, amount, how, and the M-Pesa code.' },
      { el: 'h3::Jobs', say: 'Jobs: every job ever done for them.' },
      { el: 'a[href$="/edit"]', say: 'Edit opens every field.', do: tap('a[href$="/edit"]') },
      { el: 'input[name=full_name]', say: 'Full name. Area. Status.' },
      { el: 'input[name=phone]', say: 'Phone, second phone, email.' },
      { el: 'input[name=account_no]', say: 'Account number, billing website ID, national ID.' },
      { el: 'input[name=plan]', say: 'Package, monthly rate in shillings, install date.' },
      { el: 'input[name=landmark]', say: 'Directions or landmark: how a technician finds the house. Notes for anything else.' },
      { el: 'select[name=cf__router_model]', say: 'Custom fields the admin added, like the router model. Save customer at the bottom.' },
    ]),
    C('fields-money-today', '6 · Money: Cash today', 2, 'fields-count', [
      { go: 'money/today', el: '#view .subtabs', say: 'Chapter six: Money. Six sections: Today, Record, Bills, Customers, Statements, Report. Some have a second row of pages.' },
      { el: '#m-body .kpis', say: 'Cash today. First: customer payments this month, other cash in like hotspot, and expenses logged.' },
      { el: '#m-body h3', say: 'Then each area: the bank balance from the last count, the M-Pesa float against its target, bills still owing, and cash after bills: bank plus M-Pesa minus what is owed.' },
      { el: '#m-body .alert', say: 'The alerts: float below target, cash after bills negative, bills due, Friday count due, missing receipts.' },
      { el: 'a[href="#money/count"]', say: 'And three shortcuts: Cash count, Log expense, Cash ahead.' },
    ]),
    C('fields-count', '7 · Count the cash', 1, 'fields-expense', [
      { go: 'money/count', el: '#mc select[name=area]', say: 'Chapter seven: Count the cash. The area and the date.' },
      { el: 'input[name=bank]', say: 'Bank balance, from the bank app. M-Pesa balance, from the business account. Either may be left empty.' },
      { el: 'input[name=counted_by]', say: 'Counted by, and a note for Jerry if something needs saying.' },
      { el: 'h3::Recent', say: 'Recent counts below. The × removes a wrong one.' },
    ]),
    C('fields-expense', '8 · Money out', 2, 'fields-in', [
      { go: 'money/expense', el: '#me-sms', say: 'Chapter eight: Money out. Paste the M-Pesa confirmation message here and tap Read the message: it fills the code, amount, payee, date and the new balance.' },
      { el: '#me select[name=area]', say: 'Area and date.' },
      { el: 'input[name=payee]', say: 'Paid to: start typing and known payees appear. Category: what kind of cost.' },
      { el: 'input[name=amount]', say: 'Amount in shillings. Paid from: M-Pesa, bank or cash. The M-Pesa or bank code.' },
      { el: 'select[name=receipt]', say: 'Receipt: digital, paper and filed, or none, chase it. No receipt stays on the list until it is found.' },
      { el: '#me details summary', say: 'More details: who approved it, VAT on the receipt, the supplier\'s KRA PIN for VAT, and a note. If the payee matches a bill, a tick box offers to count it against that bill.' },
      { el: '#me button[type=submit]', say: 'Save expense. This month\'s expenses are listed below, with a receipt pill.' },
    ]),
    C('fields-in', '9 · Money in', 1, 'fields-bills', [
      { go: 'money/in', el: '#mi select[name=category]', say: 'Chapter nine: Money in, for money that is not a customer\'s monthly payment: hotspot, installation fee, reconnection fee, equipment sale, other.' },
      { el: 'input[name=amount]', say: 'Amount, and where it was received: M-Pesa, bank or cash.' },
      { el: 'input[name=from_name]', say: 'From whom, the M-Pesa code, and a note. Save cash in.' },
    ]),
    C('fields-bills', '10 · Bills', 2, 'fields-payrun', [
      { go: 'money/bills', el: '#m-body .row', say: 'Chapter ten: Bills. The arrows move between months.' },
      { el: '#m-body table', say: 'Each bill: name and category, the due day, the amount, what is paid, what is owing. Pay opens the pay sheet; the pencil changes the amount or removes the bill.' },
      { el: '[data-copy]', say: 'Copy last month\'s bills makes the new month in one tap.' },
      { el: '#mb input[name=name]', say: 'Add a bill: area, the name, the amount, the due day of the month, the category, and Pay to: the paybill and account, or the phone number the money goes to.' },
    ]),
    C('fields-payrun', '10b · Pay run', 2, 'fields-collections', [
      { go: 'money/payrun', el: '#pr-build', say: 'The Pay run: what to pay today. Build today\'s list collects the bills that are due and the staff whose pay day has come.', do: tap('#pr-build') },
      { el: '#m-body .kpis', say: 'To pay now, coming in three days, and sent this month.' },
      { el: '#m-body .list .item', say: 'Each line: a bill or a person, the amount, and the number to pay. Copy number, then send it in the M-Pesa app.' },
      { el: '.pr-sent', say: 'Back in Zuri, tap Sent, type the M-Pesa code, and it is recorded as an expense. Skip puts it off for now.' },
      { go: 'admin/staff', el: '#sf-add', say: 'Staff and pay, under Admin: everyone Zuri pays, with their M-Pesa number, salary and pay day. Only finance and the partners see it.' },
    ]),
    C('fields-collections', '11 · Who paid', 2, 'fields-projection', [
      { go: 'money/collections', el: '#m-body .kpis', say: 'Chapter eleven: Who paid. Collected against expected, how many paid in full, late or part-paid and what they still owe, and not due yet.' },
      { el: '#m-body .subtabs', say: 'Late, Part paid, No history, Not due yet, Paid, All.' },
      { el: '#m-body .list .item', say: 'Each customer: rate, what they paid this month, when they ran out or renew, how reliably they pay. Call and WhatsApp buttons for the late ones.' },
    ]),
    C('fields-projection', '12 · Next 30 days', 2, 'fields-statements', [
      { go: 'money/projection', el: '#m-body .kpis', say: 'Chapter twelve: the next thirty days. The lowest point and when, the month-end balance, expected money in, bills still to pay, and the upside if late payers pay.' },
      { el: '#mp-chart', say: 'The chart: the balance day by day.' },
      { el: '#mp-start', say: 'Start from today\'s balance: type it if there is no fresh count. Update redraws.' },
      { el: '#mp-x input[name=amount]', say: 'One-off money in or out: a day, an amount with a minus for money out, and what it is. Funding from Jerry, a generator repair.' },
      { el: '#m-body table', say: 'Day by day: customers, other in, bills out, one-offs, balance, and a note of which bills land that day.' },
    ]),
    C('fields-statements', '13 · Bank & M-Pesa statements', 2, 'fields-sort', [
      { go: 'money/statements', el: '#m-body .list', say: 'Chapter thirteen: Statements. Every account money passes through: name, kind, area, owner, how far the statement goes, the balance, and how many lines still to sort.' },
      { el: '#st-acct', say: 'Import: which account, and the file: Excel, CSV, or the M-Pesa PDF. Repeats are skipped.' },
      { el: '#st-add input[name=name]', say: 'Add an account: name, kind, which area if any, and whose it is.' },
    ]),
    C('fields-sort', '14 · Sort them', 2, 'fields-books', [
      { go: 'money/sort', el: '#so-acct', say: 'Chapter fourteen: Sort them. All accounts or one; to sort, or already sorted.' },
      { el: '#so-bulk', say: 'Tick several, pick one category, Sort ticked.' },
      { el: '#view .so-cat', say: 'Each line: the description, date, account, code, and the amount. Choose the category.' },
      { el: '.so-always', say: 'Always: teach Zuri so every line like this sorts itself next time.' },
    ]),
    C('fields-books', '15 · Profit by month', 1, 'fields-report', [
      { go: 'money/books', el: '#m-body .kpis', say: 'Chapter fifteen: Profit by month. Income, expenses and profit for the latest month.' },
      { el: '#bk-pie', say: 'Where the money went, by category.' },
      { el: '#m-body table', say: 'The table: every income and expense category, month by month, with totals and profit. Transfers between our own accounts and owner money are left out.' },
    ]),
    C('fields-report', '16 · Friday report and bringing in files', 2, 'fields-admin', [
      { go: 'money/report', el: 'pre.report', say: 'Chapter sixteen: the Friday report writes itself from this week\'s numbers.' },
      { el: '#mr-copy', say: 'Copy for WhatsApp, and Export to CSV for a spreadsheet of the whole month.' },
      { go: 'import', el: '#im-kind', say: 'Bring in a file: a customer list or customer payments, from Billnasi or the second billing website.' },
      { el: '#im-file', say: 'Area if the file does not say, then the file. Zuri reads the headings and asks you to check them.' },
    ]),
    C('fields-admin', '17 · Admin', 3, 'fields-me', [
      { go: 'admin/people', el: '#a-body form[data-id]', say: 'Chapter seventeen: Admin. People: everyone who signed up. Their job: field tech, call center, office staff with a finance or technical department, or admin. Their area. On or off. Save.' },
      { go: 'admin/visibility', el: '#a-body', say: 'Who sees what: for each customer field, which jobs may see it. Untick ID numbers for field techs, for example.' },
      { go: 'admin/fields', el: '#af input[name=label]', say: 'Custom fields: add your own customer field. A name, a kind: text, number, date, yes or no, or pick from a list, and the choices.' },
      { go: 'admin/areas', el: '#aa input[name=code]', say: 'Areas: each area\'s name, its M-Pesa float target, and whether it is in use. Add Zuri C here when it opens.' },
    ]),
    C('fields-me', '18 · Me', 1, null, [
      { go: 'me', el: '#view .card', say: 'Chapter eighteen: Me. Your job and area, and whether you are online.' },
      { el: 'h3::Waiting', say: 'Waiting to send: work saved on this phone that has not reached the server yet. Send now, Retry, or Discard.' },
      { el: 'a[href="#learn"]', say: 'More: Learn Zuri, the Tester checklist, Admin, and Bring in a file.' },
      { el: '#me-theme', say: 'Screen: like my phone, light, or dark.' },
      { el: '#me-out', say: 'Sign out, and the version line. That is every screen and every field. Thank you for watching.' },
    ]),
  ];
  if (Z.lessons) Z.lessons.push(...CH);
})();
